# RedisのパスワードをBase64でエンコードして保持
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  # password: "my-redis-password" を Base64エンコードしたもの
  password: "bXktcmVkaXMtcGFzc3dvcmQ="
