# Redis Deploymentに対する安定したアクセスを提供するClusterIPサービス
apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  # typeのデフォルトはClusterIP
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
